import test from 'node:test';
import assert from 'node:assert/strict';
import {
  parseTimestamp,
  parseSrt,
  parseWebVtt,
  parseTtml,
  activeCueAt,
  alignCueByOverlap,
} from '../extension/src/subtitles.js';

test('parseTimestamp handles SRT, VTT, TTML, and normalized forms', () => {
  assert.equal(parseTimestamp('01:02:03,456'), 3723.456);
  assert.equal(parseTimestamp('02:03.500'), 123.5);
  assert.equal(parseTimestamp('1.5s'), 1.5);
  assert.equal(parseTimestamp('1500ms'), 1.5);
  assert.equal(parseTimestamp('2m'), 120);
  assert.equal(parseTimestamp('12f', { frameRate: 24 }), 0.5);
  assert.equal(parseTimestamp('50t', { tickRate: 100 }), 0.5);
  assert.equal(parseTimestamp('00:00:01:12', { frameRate: 24 }), 1.5);
  assert.equal(parseTimestamp(2.25), 2.25);
  assert.ok(Number.isNaN(parseTimestamp('not-a-time')));
  assert.ok(Number.isNaN(parseTimestamp('-1s')));
  assert.ok(Number.isNaN(parseTimestamp('00:61:00.000')));
});

test('parseSrt handles BOM, CRLF, cue coordinates, markup, and multiline text', () => {
  const source = [
    '\uFEFF1',
    '00:00:01,000 --> 00:00:03,250',
    '<i>Hallo</i> &amp; willkommen!',
    '',
    '2',
    '00:00:03,250 --> 00:00:05,000 X1:0 X2:40',
    'Wie geht es',
    'dir?',
    '',
  ].join('\r\n');

  assert.deepEqual(parseSrt(source), [
    { start: 1, end: 3.25, text: 'Hallo & willkommen!' },
    { start: 3.25, end: 5, text: 'Wie geht es\ndir?' },
  ]);
});

test('parseSrt tolerates a missing blank line between numbered cues', () => {
  const source = `1
00:00:00,000 --> 00:00:01,000
One
2
00:00:01,000 --> 00:00:02,000
Two`;

  assert.deepEqual(parseSrt(source), [
    { start: 0, end: 1, text: 'One' },
    { start: 1, end: 2, text: 'Two' },
  ]);
});

test('parseWebVtt ignores metadata blocks and parses identifiers and settings', () => {
  const source = `WEBVTT - captions

Kind: captions
Language: de

NOTE generated by a test
This is not a cue.

STYLE
::cue { color: lime; }

intro
00:00.500 --> 00:02.000 align:start position:10%
<v Anna><b>Guten Morgen</b></v>

00:02.000 --> 00:04.250
Sch\u00F6n, dich zu sehen &amp; willkommen.`;

  assert.deepEqual(parseWebVtt(source), [
    { start: 0.5, end: 2, text: 'Guten Morgen' },
    { start: 2, end: 4.25, text: 'Sch\u00F6n, dich zu sehen & willkommen.' },
  ]);
});

test('parseTtml handles namespaces, inherited timing, duration, spans, breaks, and entities', () => {
  const source = `<?xml version="1.0" encoding="UTF-8"?>
<tt xmlns="http://www.w3.org/ns/ttml" xmlns:ttp="http://www.w3.org/ns/ttml#parameter" ttp:frameRate="25">
  <body begin="1s">
    <div>
      <p begin="2s" dur="1.5s">Hallo <span>Welt</span><br/>Wie geht&apos;s?</p>
      <p begin="4s" end="6s">Bis bald &#x1F44B;</p>
    </div>
  </body>
</tt>`;

  assert.deepEqual(parseTtml(source), [
    { start: 3, end: 4.5, text: "Hallo Welt\nWie geht's?" },
    { start: 5, end: 7, text: 'Bis bald \u{1F44B}' },
  ]);
});

test('parseTtml uses declared frame timing', () => {
  const source = `<tt xmlns:ttp="urn:test" ttp:frameRate="24"><body><div>
    <p begin="00:00:01:12" dur="12f">Frame cue</p>
  </div></body></tt>`;

  assert.deepEqual(parseTtml(source), [{ start: 1.5, end: 2, text: 'Frame cue' }]);
});

test('parseTtml defaults an undeclared tick rate to one tick per second', () => {
  const source = `<tt><body><div>
    <p begin="10t" dur="2t">Tick cue</p>
  </div></body></tt>`;

  assert.deepEqual(parseTtml(source), [{ start: 10, end: 12, text: 'Tick cue' }]);
});

test('parseTtml divides clock-time subframes by the declared subframe rate', () => {
  const source = `<tt xmlns:ttp="urn:test" ttp:frameRate="25" ttp:subFrameRate="4"><body><div>
    <p begin="00:00:01:12.2" dur="1s">Subframe cue</p>
  </div></body></tt>`;

  assert.deepEqual(parseTtml(source), [{ start: 1.5, end: 2.5, text: 'Subframe cue' }]);
});

test('parseTtml uses the earlier of end and begin plus duration', () => {
  const source = `<tt><body><div>
    <p begin="1s" end="10s" dur="2s">Bounded cue</p>
  </div></body></tt>`;

  assert.deepEqual(parseTtml(source), [{ start: 1, end: 3, text: 'Bounded cue' }]);
});

test('subtitle parsers return cues in chronological order', () => {
  const source = `2
00:00:03,000 --> 00:00:04,000
Later

1
00:00:01,000 --> 00:00:02,000
Earlier`;

  assert.deepEqual(parseSrt(source), [
    { start: 1, end: 2, text: 'Earlier' },
    { start: 3, end: 4, text: 'Later' },
  ]);

  const ttml = `<tt><body><div>
    <p begin="3s">Later</p>
    <p begin="1s">Earlier</p>
    <p begin="5s" dur="1s">Last</p>
  </div></body></tt>`;
  assert.deepEqual(parseTtml(ttml), [
    { start: 1, end: 3, text: 'Earlier' },
    { start: 3, end: 5, text: 'Later' },
    { start: 5, end: 6, text: 'Last' },
  ]);
});

test('activeCueAt uses inclusive starts, exclusive ends, and prefers the latest overlap', () => {
  const first = { start: 0, end: 2, text: 'first' };
  const second = { start: 1, end: 3, text: 'second' };
  const cues = [first, second];

  assert.equal(activeCueAt(cues, 0), first);
  assert.equal(activeCueAt(cues, 1.5), second);
  assert.equal(activeCueAt(cues, 3), null);
  assert.equal(activeCueAt(cues, Number.NaN), null);
});

test('alignCueByOverlap selects maximum overlap and uses center proximity for ties', () => {
  const source = { start: 10, end: 14, text: 'source' };
  const candidates = [
    { start: 8, end: 11, text: 'small overlap' },
    { start: 9, end: 13, text: 'best' },
    { start: 11, end: 15, text: 'equal overlap but equally centered' },
  ];

  assert.equal(alignCueByOverlap(source, candidates), candidates[1]);
  assert.equal(alignCueByOverlap(source, [{ start: 14, end: 15, text: 'touching only' }]), null);
  assert.equal(alignCueByOverlap(null, candidates), null);
});
